import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

// POST /api/relationships - Create a new relationship (Partner A)
export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()

    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { relationshipDescription } = await request.json()

    // Check if user already has an active relationship
    const { data: existing } = await supabase
      .from('relationships')
      .select('*')
      .or(`partner_a_id.eq.${user.id},partner_b_id.eq.${user.id}`)
      .eq('status', 'active')
      .single()

    if (existing) {
      return NextResponse.json(
        { error: 'You already have an active relationship' },
        { status: 400 }
      )
    }

    // Create relationship (link_code will be auto-generated by database trigger)
    const { data: relationship, error: createError } = await supabase
      .from('relationships')
      .insert({
        partner_a_id: user.id,
        partner_b_id: null, // Will be set when partner B joins
        status: 'pending',
        relationship_description: relationshipDescription || null,
      })
      .select()
      .single()

    if (createError) {
      return NextResponse.json({ error: createError.message }, { status: 500 })
    }

    return NextResponse.json({
      success: true,
      relationship,
      linkCode: relationship.link_code,
    })
  } catch (error) {
    console.error('Create relationship error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// GET /api/relationships - Get user's relationship
export async function GET() {
  try {
    const supabase = await createClient()

    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get user's relationship
    const { data: relationship, error: fetchError } = await supabase
      .from('relationships')
      .select(`
        *,
        partner_a:profiles!partner_a_id(*),
        partner_b:profiles!partner_b_id(*)
      `)
      .or(`partner_a_id.eq.${user.id},partner_b_id.eq.${user.id}`)
      .eq('status', 'active')
      .single()

    if (fetchError && fetchError.code !== 'PGRST116') { // PGRST116 = no rows returned
      return NextResponse.json({ error: fetchError.message }, { status: 500 })
    }

    return NextResponse.json({ relationship: relationship || null })
  } catch (error) {
    console.error('Get relationship error:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
